apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-balance-controller-manager
  namespace: kube-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: kube-balance-controller-manager
      containers:
      - name: manager
        image: docker.io/lokeshllkumar/kube-balance:latest
        command:
        - /manager
        args:
        - --leader-elect=true
        - --recheck-interval=2m
        - --max-evictions-per-node-per-cycle=2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
      terminationGracePeriodSeconds: 10