apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensitive-app
  labels:
    app: sensitive-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensitive-app
  template:
    metadata:
      labels:
        app: sensitive-app
        workload.k8s.io/type: io-sensitive
    spec:
      containers:
      - name: main
        image: busybox:1.36
        command: ["sh", "-c", "echo 'This is an I/O sensitive app' && sleep 3600"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"